# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

# R versions
r:
  - oldrel
  - release
  - devel

# Operating systems to build on

os:
  - linux
  - osx

# Linux options
dist: xenial
cache: packages

# Apparently R-devel for OSX is a pain on most CI platforms, so I'm excluding
# it from our builds. See below for more details on the problem
# https://community.rstudio.com/t/r-devel-error-on-travis-ci-and-appveyor/2708

# Additionally, excluding OSX for all non-master branch builds. We'll get those
# errors (if they exist) at pull request time and can evaluate from there.

# test if statement in exclude: w/ the following.
# echo '{"branch": "something", "os": "somethingelse"}' | travis-conditions eval "branch != master && os = osx"

jobs:
  exclude:
  - os: osx
    r: devel
  - if: branch != master && os = osx
